# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
logo:                '/assets/logo/logo_with_text.png'
title:               'Talang Soft Limited'
description:         'Happily Coding Ever After'
url:                 http://talangsoft.org
baseurl:             http://www.talangsoft.org/
paginate:            5

# About/contact
author:
  name:              Talang Soft Limited
  url:               https://twitter.com/talangsoft
  email:             contact@talangsoft.org

# Custom vars
version:             1.0.1
