# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Talang Soft Limited
tagline:             ''
description:         '<a href="http://www.talangsoft.org/">Talang Soft Limited</a> <br/> Happily Coding Ever After'
url:                 http://talangsoft.org
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Timea Molnar
  url:               https://twitter.com/montymea
  email:             timea.molnar@talangsoft.com

# Custom vars
version:             1.0.1
